//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity
    {
        public int IdentityId { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Descriptio { get; set; }
        public string LogoURL { get; set; }
        public string Unvan { get; set; }
    }
}
